name: flutter_aulas
version: 1.0.0
environment:
  sdk: '>=2.19.6 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  convenient_test_dev: ^1.0.0
  flutter_test:
    sdk: flutter
dependencies:
  flutter_riverpod: ^2.4.4
  convenient_test: ^1.0.0
  device_preview: ^1.1.0
  http: ^1.2.1
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf